# Generated by Django 4.2.5 on 2023-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_blog_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="created_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="updated_date",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_created",
            new_name="created",
        ),
        migrations.AddField(
            model_name="comment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
