# Generated by Django 4.2.5 on 2023-09-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_created_date_blog_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_pic",
            new_name="profile_img",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="blog_image",
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_img",
            field=models.ImageField(blank=True, null=True, upload_to="blog_imgs/"),
        ),
    ]
